### ISSUE TITLE
FreeBSD port/package created!

### ISSUE THREAD

**Issue by zi0r** [gquintard/vmod_fileserver#1]
https://cgit.freebsd.org/ports/commit/?id=01d001339cfac6cfd842cf2cebc057f3db0e3330

**Comment by gquintard** [comment]
I appreciate the vote of confidence!

I've noticed this:
```
+post-extract:
+	${REINPLACE_CMD} 's|python3|${PYTHON_VERSION}|g' ${WRKSRC}/cargo-crates/varnish-*/src/lib.rs
```

Is there something I could do to save you that operation?

**Comment by zi0r** [comment]
Perhaps some way to specify the python binary; maybe via environment variable or the like?

FreeBSD doesn't install a python or python3 symlink anymore.  It's just pythonX.Y for the specific version that is installed--which could be multiple different ones at the moment.

**Comment by gquintard** [comment]
got it, I'll track this here, and will update this ticket once it makes it's way here

**Comment by gquintard** [comment]
hi there, I just pushed `v0.0.2` which should close this (just export the `PYTHON` variable). Please yell if it doesn't!
