### ISSUE TITLE
Patches to fix build under arm/powerpc

### ISSUE THREAD

**Issue by zi0r** [gquintard/vmod_fileserver#2]
These were added by a fellow FreeBSD-er to resolve the build under arm/powerpc:
https://cgit.freebsd.org/ports/tree/www/varnish-libvmod-fileserver/files

**Comment by gquintard** [comment]
Hi @zi0r, thanks for pointing me at those, I believe this is fixed in version `0.0.2`, after @pkubaj pointed it out here: https://github.com/gquintard/varnish-rs/issues/14
Would you be able to confirm this?

**Comment by zi0r** [comment]
Ah, this does indeed look like the same stuff.  Sorry for the noise!
